using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using DAO;
using Microsoft.ApplicationBlocks.Data;

namespace TestForm
{
    public partial class FormHoaDonChiTiet : Form
    {
        string MaPhieu;
        private SqlConnection con;
        public FormHoaDonChiTiet()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
         //   sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        public FormHoaDonChiTiet(string s)
        {
            InitializeComponent();
            this.MaPhieu = s;
            txtMaphieu.Text = MaPhieu;
        }
        public void bindings()
        {
            txtMaMH.DataBindings.Clear();
            txtMaMH.DataBindings.Add("Text", grcHDCT.DataSource, "MaMH");
            txtNhanVien.DataBindings.Clear();
            txtNhanVien.DataBindings.Add("Text", grcHDCT.DataSource, "MaNV");
            txtSoLuong.DataBindings.Clear();
            txtSoLuong.DataBindings.Add("Text", grcHDCT.DataSource, "SoLuong");
           txtMaLoaiTien.DataBindings.Clear();
            txtMaLoaiTien.DataBindings.Add("Text", grcHDCT.DataSource, "MaLoaiTien");
            txtThanhTien.DataBindings.Clear();
            txtThanhTien.DataBindings.Add("Text", grcHDCT.DataSource, "ThanhTien");
        }
        private void textBox3_TextChanged(object sender, EventArgs e)
        {
                
        }

        private void FormHoaDonChiTiet_Load(object sender, EventArgs e)
        {
            DataTable dt = new DataTable();
            con = DAO_DATABASE.OpenConnect();
            dt = SqlHelper.ExecuteDataset(con, "PR_HOADONCHITIET_XEMCHITIET", txtMaphieu.Text).Tables[0];
            grcHDCT.DataSource = dt;

        }

        private void grdHDCT_Click(object sender, EventArgs e)
        {
         
        }

        private void gridView1_Click(object sender, EventArgs e)
        {
            bindings();
        }

        private void btnThem_Click(object sender, EventArgs e)
        {
            try
            {
                con = DAO_DATABASE.OpenConnect();
                SqlHelper.ExecuteNonQuery(con, "PR_HOADONCHITIET_THEM", txtMaphieu.Text, txtMaMH.Text, txtNhanVien.Text, txtSoLuong.Text, txtMaLoaiTien.Text);
                DAO_DATABASE.CloseConnect(con);
                FormHoaDonChiTiet_Load(sender,e);

            }
            catch(Exception ex) {
                MessageBox.Show("Loi");
            }
        }

        private void btnXoa_Click(object sender, EventArgs e)
        {
            try
            {
                con = DAO_DATABASE.OpenConnect();
                SqlHelper.ExecuteNonQuery(con, "PR_HOADONCHITET_XOA_MH_KH", txtMaphieu.Text, txtMaMH.Text);
                DAO_DATABASE.CloseConnect(con);
                FormHoaDonChiTiet_Load(sender, e);

            }
            catch (Exception ex)
            {
                MessageBox.Show("Loi");
            }

        }

        private void btnSua_Click(object sender, EventArgs e)
        {
            try
            {
                con = DAO_DATABASE.OpenConnect();
                SqlHelper.ExecuteNonQuery(con, "PR_HOADONCHITIET_SUA", txtMaphieu.Text, txtMaMH.Text, txtNhanVien.Text, txtSoLuong.Text, txtMaLoaiTien.Text);
                DAO_DATABASE.CloseConnect(con);
                FormHoaDonChiTiet_Load(sender, e);

            }
            catch (Exception ex)
            {
                MessageBox.Show("Loi" +ex);
            }
        }
    }
}
