using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.SqlClient;
using BUS;
using DTO;
namespace TestForm
{
    public partial class FormMatHang : Form
    {
        public FormMatHang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

     
      
        private void label3_Click(object sender, EventArgs e)
        {

        }

        private void navBarGroupControlContainer1_Click(object sender, EventArgs e)
        {

        }
        private void LoadData()
        {
            grcMatHang.DataSource = BUS_MATHANG.HienThi_All();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
                //MatHangInfo mh = new MatHangInfo()
            try
            {
                MatHangInfo mh = new MatHangInfo(txtMaMH.Text, txtTenMH.Text, float.Parse(txtSoLuong.Text), float.Parse(txtDonGia.Text), float.Parse(txtGiaBan.Text), txtTenNCC.Text, dtpNgayNhap.Value, txtMaLoaiTien.Text);
                BUS_MATHANG.Them_MatHang(mh);
                DialogResult dr = MessageBox.Show("Thêm thành công");
                if (dr == DialogResult.OK)
                {
                    LoadData();
                    
                }

            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi" + ex.ToString());
            }
            
        }

        private void FormMatHang_Load(object sender, EventArgs e)
        {
             
            
        }
        public void bindings()
        {
            txtMaMH.DataBindings.Clear();
            txtMaMH.DataBindings.Add("Text",grcMatHang.DataSource, "MaMH");
            txtTenMH.DataBindings.Clear();
            txtTenMH.DataBindings.Add("Text", grdMatHang.DataSource, "TenMH");
            txtSoLuong.DataBindings.Clear();
            txtSoLuong.DataBindings.Add("Text", grcMatHang.DataSource, "SoLuong");
            txtDonGia.DataBindings.Clear();
            txtDonGia.DataBindings.Add("Text", grcMatHang.DataSource, "DonGia");
            txtGiaBan.DataBindings.Clear();
            txtGiaBan.DataBindings.Add("Text", grcMatHang.DataSource, "GiaBan");
            txtTenNCC.DataBindings.Clear();
            txtTenNCC.DataBindings.Add("Text", grcMatHang.DataSource, "MaNCC");
            dtpNgayNhap.DataBindings.Clear();
            dtpNgayNhap.DataBindings.Add("Value",grcMatHang.DataSource,"NgayNhap");
            txtMaLoaiTien.DataBindings.Clear();
            txtMaLoaiTien.DataBindings.Add("Text", grcMatHang.DataSource, "MaLoaiTien");
            txtSoLuongCon.DataBindings.Clear();
            txtSoLuongCon.DataBindings.Add("Text", grcMatHang.DataSource, "SoLuongCon");

         }
        private void grcMatHang_Click(object sender, EventArgs e)
        {
                bindings();
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
           try
            {
                MatHangInfo mh = new MatHangInfo(txtMaMH.Text, txtTenMH.Text, float.Parse(txtSoLuong.Text), float.Parse(txtDonGia.Text), float.Parse(txtGiaBan.Text), txtTenNCC.Text, dtpNgayNhap.Value, txtMaLoaiTien.Text);
                BUS_MATHANG.Sua_MatHang(mh);
                DialogResult dr = MessageBox.Show("Sua thành công");
                if (dr == DialogResult.OK)
                {
                    LoadData();
                }

           }
           catch (Exception ex)
           {
              MessageBox.Show("Lỗi" + ex.ToString());
           }
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                BUS_MATHANG.Xoa_MatHang(txtMaMH.Text);
                DialogResult dr = MessageBox.Show("Xoa thành công");
                if (dr == DialogResult.OK)
                {
                    LoadData();
                }

            }
            catch (Exception ex)
            {
                MessageBox.Show("Lỗi" + ex.ToString());
            }
        }
    }
}
