using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using BUS;
using DTO;
namespace TestForm
{
    public partial class FormPhanQuyen : Form
    {
        public FormPhanQuyen()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
       

        private void grcMatHang_Click(object sender, EventArgs e)
        {
           
          
        }

        private void grdPhanQuyen_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            if (grdPhanQuyen.FocusedRowHandle >= 0)
            {
                cmbMaQuyen.Text = grdPhanQuyen.GetFocusedRowCellValue("MaQuyen").ToString();
                txtMaNV.Text = grdPhanQuyen.GetFocusedRowCellValue("MaNV").ToString();
                txtMatKhau.Text = grdPhanQuyen.GetFocusedRowCellValue("MatKhau").ToString();
                txtTenDN.Text = grdPhanQuyen.GetFocusedRowCellValue("TenDangNhap").ToString();
            }
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                PhanQuyenInfo nv = new PhanQuyenInfo(cmbMaQuyen.Text,txtMaNV.Text,txtMatKhau.Text,txtTenDN.Text);
                BUS_PHANQUYEN.Them_TaiKhoan(nv);
                DialogResult dr = MessageBox.Show("Thêm thành công");
                if (dr == DialogResult.OK)
                {
                    FormPhanQuyen_Load(sender,e);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loi");
            }
        }

        private void FormPhanQuyen_Load(object sender, EventArgs e)
        {
            grcPhanQuyen.DataSource = BUS_PHANQUYEN.HienThi_All();

        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                PhanQuyenInfo nv = new PhanQuyenInfo(cmbMaQuyen.Text, txtMaNV.Text, txtMatKhau.Text, txtTenDN.Text);
                BUS_PHANQUYEN.Sua_TaiKhoan(nv);
                DialogResult dr = MessageBox.Show("Sua thành công");
                if (dr == DialogResult.OK)
                {
                    FormPhanQuyen_Load(sender, e);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loi");
            }
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
               
                BUS_PHANQUYEN.Xoa_TaiKhoan(txtMaNV.Text);
                DialogResult dr = MessageBox.Show("Xoa thành công");
                if (dr == DialogResult.OK)
                {
                    FormPhanQuyen_Load(sender, e);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loi");
            }
        }
    }
}
